### PR TITLE
Add info/visualization on what actually ended up in the final set

### PR DESCRIPTION
**Pull request by davidlmobley**
This adds a notebook which tries to identify which MOLECULES ended up in the final set, as well as visualization thereof. @vtlim I'd appreciate review when you have time.

### CODE REVIEW

**Comment by vtlim** [comment]
@davidlmobley - Did you upload the *.ipynb? I'm only seeing six files added, but none are the notebook.

**Comment by dfhahn** [comment]
I've added the set_v03_non_redundant which is now used in the publication. But `find_benchmark_molecules.ipynb` does not yet show how to get from the initial set to this one.

**Comment by j-wags** [comment]
Ha! @dfhahn it looks like your SMILES file may be formatted as `'f{smi}'` instead of `f'{smi}'` :-) Could you try making it again?

https://github.com/MobleyLab/benchmarkff/blob/d446f9133bdf2955d36110679962f1435e87b0f9/molecules/set_v03_non_redundant/trim3_full_qcarchive.smi#L1-L10

**Comment by dfhahn** [comment]
> Ha! @dfhahn it looks like your SMILES file may be formatted as `'f{smi}'` instead of `f'{smi}'` :-) Could you try making it again?
> 
Oh thanks for spotting this, @j-wags ! It's fixed.

**Pull request merged**
